### ISSUE TITLE
Warning: Can't add secret mask for empty string in ##[add-mask] command. 

### ISSUE THREAD

**Issue by techvsi-catvu** [wearesection/sftp-remote#5]
> Warning: Can't add secret mask for empty string in ##[add-mask] command.

This warning shows up when uploading package to server:

![Screenshot 2024-07-11 at 13 07 12](https://github.com/wearesection/sftp-remote/assets/144098182/783b489d-4cd4-452f-b268-0db272ce1438)

**Comment by s4keeiyuan** [comment]
i suspect this warning is triggered from https://github.com/vucat12/sftp-remote/blob/4424e3d787e4846f9651f2d60629cbbb37d0954b/index.js#L20

**Comment by s4keeiyuan** [comment]
thank you @techvsi-catvu
